create folder structure and about page switch to tsx
Jula000/photostudio pull request #13
Opened 2024-06-30 03:03 UTC by Jula000

2024-06-30 03:50 UTC, yevhenii-horbenko requested changes
good job! molodiec
I have a few suggestions

2024-06-30 03:50 UTC, yevhenii-horbenko commented on src/app/about/page.tsx
> +import AboutPage from "../../components/aboutPage/AboutPage";
please fix folder name to AboutPage

2024-06-30 03:50 UTC, yevhenii-horbenko commented on src/app/page.tsx
> +export default function home() {
why did you change the name?

2024-06-30 03:50 UTC, yevhenii-horbenko commented on src/components/HomePage/About/AboutComponent.tsx
> -export default function AboutSection() {
Please rename the file and the component name to be AboutSection

2024-06-30 03:50 UTC, yevhenii-horbenko commented on src/components/HomePage/FAQ/FaqComponent.tsx
> +    <div className="bg-black text-white p-8">
consider removing bg-black

2024-06-30 03:50 UTC, yevhenii-horbenko commented on src/components/HomePage/Hero/HeroSection.tsx
> +import imgBg from "../../../../public/hero-bg.png";
could you please try to use @public/hero-bg.png 
IIRC it should work

2024-06-30 03:50 UTC, yevhenii-horbenko commented on src/components/HomePage/Hero/HeroSection.tsx
> -          <GlossyButton />
Please remove glossybutton if you dont use it

2024-06-30 03:50 UTC, yevhenii-horbenko commented on src/components/common/Header.tsx
> +          </p>
You probably don't need p here, at most you need a div

2024-07-01 19:48 UTC, yevhenii-horbenko requested changes

2024-07-01 19:48 UTC, yevhenii-horbenko commented on src/app/about/page.tsx
> +import AboutPage from "../../components/AboutPage/AboutPage";
Why do you import it like that?
shouldn't be path be like:
import AboutPage from "../../components/AboutPage";?

2024-07-01 19:48 UTC, yevhenii-horbenko commented on src/app/page.tsx
> +import PhotoGrid from "../components/HomePage/PhotoGrid/PhotoGrid";
could you please fix this import?

2024-07-01 19:48 UTC, yevhenii-horbenko commented on src/app/page.tsx
> +import Portfolio from "../components/HomePage/Portfolio/Portfolio";
same

2024-07-01 19:48 UTC, yevhenii-horbenko commented on src/app/page.tsx
> +import FaqComponent from "../components/HomePage/FAQ/FaqComponent";
why dont you just name this FAQSection?

2024-07-01 19:48 UTC, yevhenii-horbenko commented on src/app/page.tsx
> +      <AboutComponent />
Why did you rename it?

2024-07-01 19:48 UTC, yevhenii-horbenko commented on src/app/page.tsx
>        <ServiceComponent />
Please dont add Component at the end as it's redundant

2024-07-01 19:48 UTC, yevhenii-horbenko commented on src/components/HomePage/About/AboutSection.tsx
> +const AboutComponent: React.FC = () => {
Please rename the variable name to match file name

2024-07-01 20:31 UTC, yevhenii-horbenko commented on src/components/common/ServicePart.tsx
> +const ServicePart: React.FC<ServiceSectionProps> = ({
please rename the interface as well
you forgot to update ServiceSectionProps

2024-07-01 20:38 UTC, yevhenii-horbenko requested changes

2024-07-01 20:38 UTC, yevhenii-horbenko commented on src/components/common/ServicePart.tsx
> +const ServicePart: React.FC<ServiceSectionProps> = ({
please rename the interface as well
you forgot to update ServiceSectionProps

2024-07-01 20:38 UTC, yevhenii-horbenko commented on src/components/HomePage/Service/index.tsx
> +const ServiceSection: React.FC = () => {
please update the name to match folder name

2024-07-01 20:38 UTC, yevhenii-horbenko commented on src/components/common/ServicePart.tsx
> +const ServicePart: React.FC<ServiceSectionProps> = ({
I guess you can name this file ServiceHighlights
Tbh servicepart name is a bit confusing

2024-07-01 22:57 UTC, yevhenii-horbenko requested changes
the last one

2024-07-01 22:57 UTC, yevhenii-horbenko commented on src/app/page.tsx
> +import FaqSection from "../components/HomePage/FaqSection";
beautiful

2024-07-01 22:57 UTC, yevhenii-horbenko commented on src/app/page.tsx
> +import FaqSection from "../components/HomePage/FaqSection";
luv it

2024-07-01 22:57 UTC, yevhenii-horbenko commented on src/components/HomePage/ServiceSection/index.tsx
> +import ServicePart from "../../common/ServiceHighlights";
name doesn't match the file

2024-07-01 23:02 UTC, Jula000 commented on src/components/HomePage/ServiceSection/index.tsx
> +import ServicePart from "../../common/ServiceHighlights";
+

2024-07-01 23:32 UTC, yevhenii-horbenko approved these changes
keep it up! you inspire me!

2024-07-01 23:32 UTC, merged